version: '3.3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: 'postgres:13.1-alpine'
      container_name: 'postgree_db'
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: posterr
        POSTGRES_USER: posterr
        POSTGRES_PASSWORD: posterr123
      ports:
        - 5430:5432
  app: 
     image: 'app_posterr'
     container_name: 'app_posterr'
     environment:
        DATABASE: posterr
        DATABASE_USER: posterr
        DATABASE_HOST: postgree_db
        DATABASE_PASSWORD: posterr123
     build:
       context: .
       dockerfile: ./Dockerfile
     ports:
       - 3001:3001
     depends_on:
       - postgres
